const data = [
  {
    NAMA_ANAK: "ABYAN HAMZAH",
    JENIS_KELAMIN: 0,
    UMUR: 5,
    TB: 66.5,
    BB: 7.9,
  },
  {
    NAMA_ANAK: "ADINDA FITRI .T",
    JENIS_KELAMIN: 1,
    UMUR: 49,
    TB: 103.5,
    BB: 16,
  },
  {
    NAMA_ANAK: "AERIN SAFA RAMADANI",
    JENIS_KELAMIN: 1,
    UMUR: 3,
    TB: 61.5,
    BB: 5.9,
  },
  {
    NAMA_ANAK: "AFSHA NURVADANA",
    JENIS_KELAMIN: 1,
    UMUR: 5,
    TB: 62.7,
    BB: 6.2,
  },
  {
    NAMA_ANAK: "AHMAD ABIZAR",
    JENIS_KELAMIN: 0,
    UMUR: 5,
    TB: 65,
    BB: 7,
  },
  {
    NAMA_ANAK: "ALBY REYNAND QADDAFI",
    JENIS_KELAMIN: 0,
    UMUR: 33,
    TB: 96.5,
    BB: 14.8,
  },
  {
    NAMA_ANAK: "ALYA SYAHIRA",
    JENIS_KELAMIN: 1,
    UMUR: 11,
    TB: 56,
    BB: 62,
  },
  {
    NAMA_ANAK: "ALESHA DHUHA",
    JENIS_KELAMIN: 1,
    UMUR: 4,
    TB: 62.5,
    BB: 6,
  },
  {
    NAMA_ANAK: "ANISA DWI YANTI",
    JENIS_KELAMIN: 1,
    UMUR: 53,
    TB: 99.8,
    BB: 14.8,
  },
  {
    NAMA_ANAK: "AQILA AUFA",
    JENIS_KELAMIN: 1,
    UMUR: 48,
    TB: 110.4,
    BB: 22.6,
  },
  {
    NAMA_ANAK: "AQILA WIDYA L",
    JENIS_KELAMIN: 1,
    UMUR: 28,
    TB: 88.8,
    BB: 12,
  },
  {
    NAMA_ANAK: "ARETHA PUTRI",
    JENIS_KELAMIN: 1,
    UMUR: 4,
    TB: 66.5,
    BB: 6.7,
  },
  {
    NAMA_ANAK: "ARKA ZIKRI F",
    JENIS_KELAMIN: 0,
    UMUR: 49,
    TB: 94,
    BB: 13.2,
  },
  {
    NAMA_ANAK: "ARKHAN RAMEZA",
    JENIS_KELAMIN: 0,
    UMUR: 33,
    TB: 92,
    BB: 12.2,
  },
  {
    NAMA_ANAK: "ARYA ADITYA L",
    JENIS_KELAMIN: 0,
    UMUR: 10,
    TB: 73.5,
    BB: 8.4,
  },
  {
    NAMA_ANAK: "ARYA ELVAREL DWI P",
    JENIS_KELAMIN: 0,
    UMUR: 5,
    TB: 64.6,
    BB: 7.2,
  },
  {
    NAMA_ANAK: "AWAN FERDIANSYAH",
    JENIS_KELAMIN: 0,
    UMUR: 14,
    TB: 81,
    BB: 10.3,
  },
  {
    NAMA_ANAK: "AYRA MISHA",
    JENIS_KELAMIN: 1,
    UMUR: 53,
    TB: 105.9,
    BB: 16,
  },
  {
    NAMA_ANAK: "AZKA ARTHA",
    JENIS_KELAMIN: 0,
    UMUR: 55,
    TB: 101.3,
    BB: 15.9,
  },
  {
    NAMA_ANAK: "AZQIARA",
    JENIS_KELAMIN: 1,
    UMUR: 57,
    TB: 106.5,
    BB: 19.3,
  },
  {
    NAMA_ANAK: "BINTANG .A.N",
    JENIS_KELAMIN: 0,
    UMUR: 38,
    TB: 106,
    BB: 13.8,
  },
  {
    NAMA_ANAK: "CAHRA RISKI .A",
    JENIS_KELAMIN: 1,
    UMUR: 29,
    TB: 90,
    BB: 12,
  },
  {
    NAMA_ANAK: "CAHAYA WULANDARI",
    JENIS_KELAMIN: 1,
    UMUR: 33,
    TB: 91.9,
    BB: 12.2,
  },
  {
    NAMA_ANAK: "CELIN NUR .C",
    JENIS_KELAMIN: 1,
    UMUR: 25,
    TB: 72.6,
    BB: 9.6,
  },
  {
    NAMA_ANAK: "EGI ARIYANTO",
    JENIS_KELAMIN: 0,
    UMUR: 57,
    TB: 105.5,
    BB: 18,
  },
  {
    NAMA_ANAK: "ERSA ASYARINA",
    JENIS_KELAMIN: 1,
    UMUR: 2,
    TB: 50.4,
    BB: 59,
  },
  {
    NAMA_ANAK: "FAHRUL NURAVIANYA",
    JENIS_KELAMIN: 0,
    UMUR: 57,
    TB: 108,
    BB: 16.9,
  },
  {
    NAMA_ANAK: "FELICIA PUTRI ANGGRIANI",
    JENIS_KELAMIN: 1,
    UMUR: 19,
    TB: 81,
    BB: 9.5,
  },
  {
    NAMA_ANAK: "FELYSIA NAHLA .H",
    JENIS_KELAMIN: 1,
    UMUR: 26,
    TB: 89.7,
    BB: 13.1,
  },
  {
    NAMA_ANAK: "HALWATUZZAHRA CLARISA",
    JENIS_KELAMIN: 1,
    UMUR: 25,
    TB: 87,
    BB: 12,
  },
  {
    NAMA_ANAK: "IJAL OKTA PRASETYA",
    JENIS_KELAMIN: 0,
    UMUR: 57,
    TB: 97,
    BB: 12.7,
  },
  {
    NAMA_ANAK: "IRSAT ALVIN ALQAFARI",
    JENIS_KELAMIN: 0,
    UMUR: 36,
    TB: 100,
    BB: 10.6,
  },
  {
    NAMA_ANAK: "KALITA NASHA",
    JENIS_KELAMIN: 1,
    UMUR: 27,
    TB: 63.5,
    BB: 6.8,
  },
  {
    NAMA_ANAK: "KENZO ALRASKA",
    JENIS_KELAMIN: 0,
    UMUR: 25,
    TB: 90,
    BB: 12,
  },
  {
    NAMA_ANAK: "KHANSA ADELIA .N",
    JENIS_KELAMIN: 1,
    UMUR: 26,
    TB: 81.3,
    BB: 10.6,
  },
  {
    NAMA_ANAK: "M. ALFIAN SAPUTRA",
    JENIS_KELAMIN: 0,
    UMUR: 23,
    TB: 86,
    BB: 8.7,
  },
  {
    NAMA_ANAK: "M. LUTHFI .A",
    JENIS_KELAMIN: 0,
    UMUR: 28,
    TB: 90.5,
    BB: 13.8,
  },
  {
    NAMA_ANAK: "M. RIZHAN AL SYAZANI",
    JENIS_KELAMIN: 0,
    UMUR: 5,
    TB: 68,
    BB: 6,
  },
  {
    NAMA_ANAK: "M. DAFI AL RASYA",
    JENIS_KELAMIN: 0,
    UMUR: 31,
    TB: 86,
    BB: 12,
  },
  {
    NAMA_ANAK: "NAJWA AL NAHYIRA",
    JENIS_KELAMIN: 1,
    UMUR: 14,
    TB: 80,
    BB: 8,
  },
  {
    NAMA_ANAK: "NASELA ANANSYA .A",
    JENIS_KELAMIN: 1,
    UMUR: 19,
    TB: 78,
    BB: 9.9,
  },
  {
    NAMA_ANAK: "NAYLA ZIA ALMAHIRA",
    JENIS_KELAMIN: 1,
    UMUR: 7,
    TB: 70.5,
    BB: 69,
  },
  {
    NAMA_ANAK: "NUR AFIFAH .M",
    JENIS_KELAMIN: 1,
    UMUR: 11,
    TB: 74.5,
    BB: 8.8,
  },
  {
    NAMA_ANAK: "RAFA ARRAHSYA",
    JENIS_KELAMIN: 0,
    UMUR: 22,
    TB: 83,
    BB: 8.5,
  },
  {
    NAMA_ANAK: "RAIHAN ALIFKA ZIKRI",
    JENIS_KELAMIN: 0,
    UMUR: 15,
    TB: 77,
    BB: 9.3,
  },
  {
    NAMA_ANAK: "RAISYA AQILA",
    JENIS_KELAMIN: 1,
    UMUR: 22,
    TB: 73,
    BB: 8.7,
  },
  {
    NAMA_ANAK: "RAKA CAHYO .S",
    JENIS_KELAMIN: 0,
    UMUR: 42,
    TB: 93.6,
    BB: 12.4,
  },
  {
    NAMA_ANAK: "RAYYANDRA ALFAEZA",
    JENIS_KELAMIN: 0,
    UMUR: 5,
    TB: 69,
    BB: 8.2,
  },
  {
    NAMA_ANAK: "SABQI ATHARRAZKA",
    JENIS_KELAMIN: 0,
    UMUR: 32,
    TB: 87,
    BB: 10.6,
  },
  {
    NAMA_ANAK: "SAQUEL ISYQIANDRA",
    JENIS_KELAMIN: 0,
    UMUR: 53,
    TB: 97.5,
    BB: 13.2,
  },
  {
    NAMA_ANAK: "SASKYA MUTI",
    JENIS_KELAMIN: 1,
    UMUR: 54,
    TB: 100.5,
    BB: 14.9,
  },
  {
    NAMA_ANAK: "SATRIA BAGASKARA",
    JENIS_KELAMIN: 0,
    UMUR: 12,
    TB: 74,
    BB: 8.2,
  },
  {
    NAMA_ANAK: "SAYHAN ARSHAKA .A",
    JENIS_KELAMIN: 0,
    UMUR: 22,
    TB: 83,
    BB: 9.4,
  },
  {
    NAMA_ANAK: "SELI SRI RAMADHANI",
    JENIS_KELAMIN: 1,
    UMUR: 4,
    TB: 67,
    BB: 6.9,
  },
  {
    NAMA_ANAK: "VANIA KAISA",
    JENIS_KELAMIN: 1,
    UMUR: 3,
    TB: 60,
    BB: 5.5,
  },
  {
    NAMA_ANAK: "VIRZA ARIANSYAH",
    JENIS_KELAMIN: 0,
    UMUR: 36,
    TB: 93.3,
    BB: 12.2,
  },
  {
    NAMA_ANAK: "TEST IDEAL-IDEAL-0",
    JENIS_KELAMIN: 0,
    UMUR: 38,
    TB: 110,
    BB: 25,
  },
  {
    NAMA_ANAK: "TEST IDEAL-IDEAL-1",
    JENIS_KELAMIN: 1,
    UMUR: 38,
    TB: 110,
    BB: 25,
  },
  {
    NAMA_ANAK: "TEST TIDAK-IDEAL-IDEAL-1",
    JENIS_KELAMIN: 1,
    UMUR: 25,
    TB: 78,
    BB: 8,
  },
  {
    NAMA_ANAK: "TEST TIDAK-IDEAL-IDEAL-0",
    JENIS_KELAMIN: 0,
    UMUR: 25,
    TB: 78,
    BB: 8,
  },
];
module.exports = { data };